version: '3.8'

services:
  apigateway:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    command: ["dotnet", "APIGateway/APIGateway.dll"]
    ports:
      - "5000:80"

  fileanalisysservice:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    command: ["dotnet", "FileAnalisysService/FileAnalisysService.dll"]
    ports:
      - "5001:80"
      
  filestoringservice:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    command: ["dotnet", "FileStoringService/FileStoringService.dll"]
    ports:
      - "5002:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: postgresql_db
volumes:
  db_data: